export enum OrderStatus {
  PENDING_PAYMENT       = 'pending_payment',
  PAID                  = 'paid',
  BROADCASTING_REP      = 'broadcasting_rep',
  REP_ASSIGNED          = 'rep_assigned',
  BROADCASTING_VENDOR   = 'broadcasting_vendor',
  VENDOR_ASSIGNED       = 'vendor_assigned',
  SCHEDULED             = 'scheduled',
  REP_EN_ROUTE_PICKUP   = 'rep_en_route_pickup',
  PICKED_UP             = 'picked_up',
  WITH_VENDOR           = 'with_vendor',
  IN_PROGRESS           = 'in_progress',
  QUALITY_CHECK         = 'quality_check',
  READY_FOR_DELIVERY    = 'ready_for_delivery',
  REP_COLLECTED         = 'rep_collected',
  OUT_FOR_DELIVERY      = 'out_for_delivery',
  DELIVERED             = 'delivered',
  COMPLETED             = 'completed',
  DISPUTED              = 'disputed',
  CANCELLED             = 'cancelled',
}
